### ISSUE TITLE
migration error

### ISSUE THREAD

**Issue by hong19** [polintw/Pensieve#61]
```bash
npx sequelize db:create
npx sequelize db:migrate
npx sequelize db:seed --seed 20190214121202-init-nouns.js
npx sequelize db:seed --seed 20190329010101-admin-nations.js
{ Error: Command failed: npx sequelize db:seed --seed 20190329010101-admin-nations.js
ERROR: Cannot find module './faked/dbSeeds/nouns_nations_EN.json'

    at ChildProcess.exithandler (child_process.js:299:12)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Socket.stream.socket.on (internal/child_process.js:403:11)
    at Socket.emit (events.js:193:13)
    at Pipe._handle.close (net.js:614:12)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'npx sequelize db:seed --seed 20190329010101-admin-nations.js' }
```

Lack file `./faked/dbSeeds/nouns_nations_EN.json`

**Comment by polintw** [comment]
There is a modification to the file 
*20190329010101-admin-nations.js*
in this command:
```bash
npx sequelize db:seed --seed 20190329010101-admin-nations.js
```

after this process was set.
That's how the error happened.

fix would commit together with other fix at branch ```develop```.

**Comment by polintw** [comment]
Fixed in the latest commit on develop !

Thanks!
